services:
  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data:Z
      - ./postgres/conf/postgres.conf:/etc/postgresql/postgresql.conf
    ports:
      - 5532:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    command: [ "postgres", "-c", "config_file=/etc/postgresql/postgresql.conf" ]